# Generated by Django 4.2.27 on 2025-12-31 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitulo', models.CharField(help_text='Frase de impacto inicial', max_length=300)),
                ('descripcion', models.TextField()),
                ('en_vivo', models.BooleanField(default=False)),
                ('portada', models.ImageField(upload_to='cursos/portadas/')),
                ('precio_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_certificacion_adicional', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('horas_certificacion', models.IntegerField(default=20)),
                ('duracion_en_vivo', models.IntegerField(help_text='Horas totales de clases en vivo')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('meses_grabaciones', models.IntegerField(default=12)),
                ('grupo_whatsapp', models.BooleanField(default=True)),
                ('materiales_descargables', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('horario_clase', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo_blanco', models.FileField(help_text='Logo en formato SVG o PNG blanco', upload_to='respaldos/')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo_corto', models.CharField(help_text='Ej: Psicólogo / Arquitecto de Datos', max_length=100)),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(upload_to='instructors/')),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Estadística Descriptiva', max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_clase', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('duracion_minutos', models.IntegerField(default=15)),
                ('es_gratis', models.BooleanField(default=False, help_text='¿Es una lección de prueba?')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='cursos.instructor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='respaldos',
            field=models.ManyToManyField(blank=True, to='cursos.institucionrespaldo'),
        ),
    ]
